esphome:
  name: esp32-gardencontrol
  friendly_name: ESP32 GardenControl


  on_boot:
    priority: -100
    then:
      - switch.turn_on: gardencontrolPWRLed



esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 0s
  encryption:
    #key: "yeEOrYfHwMGuX0kWfSADb/PSPXcE7K4JRN/OcXgJGY0="


  services:
    - service: set_pulse_total
      variables:
        new_pulse_total: int
      then:
        - pulse_counter.set_total_pulses:
            id: pulse_counter_id
            value: !lambda 'return new_pulse_total;'

ota:
  - platform: esphome
    password: "8f2367541da378ad86b985949228afb6"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Gardencontrol"
    password: "12345678"

captive_portal:

mqtt:
  broker: !secret mqtt_ip
  username: !secret mqtt_user 
  password: !secret mqtt_password  

i2c:
  sda: GPIO21 
  scl: GPIO22
  scan: true
  id: bus_a

mcp23017:
  - id: 'mcp23017_top'
    i2c_id: bus_a
    address: 0x26
  - id: 'mcp23017_bot'
    address: 0x27
    i2c_id: bus_a

pcf8574:
  - id: 'pcf8575'
    address: 0x24
    pcf8575: True

ads1115:
  - address: 0x49

# Individual outputs
switch:
  - platform: gpio
    pin: GPIO12
    name: "GardenControl Status LED"
  - platform: gpio
    id: gardenControlErrorLed
    pin: GPIO2
    name: "GardenControl ERROR LED"    

  - platform: gpio
    name: "GardenControl 5V enable"
    restore_mode: ALWAYS_ON
    pin:
      mcp23xxx: mcp23017_top
      number: 3
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "GardenControl 12V enable"
    restore_mode: ALWAYS_ON
    pin:
      mcp23xxx: mcp23017_top
      number: 4
      mode:
        output: true
      inverted: false      
  - platform: gpio
    name: "GardenControl 24V enable"
    restore_mode: ALWAYS_ON
    pin:
      mcp23xxx: mcp23017_top
      number: 5
      mode:
        output: true
      inverted: false  
  - platform: gpio
    name: "GardenControl 24V 4-20mA CH1 enable"
    restore_mode: ALWAYS_ON
    pin:
      mcp23xxx: mcp23017_bot
      number: 14
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "GardenControl 24V 4-20mA CH2 enable"
    restore_mode: ALWAYS_ON
    pin:
      mcp23xxx: mcp23017_bot
      number: 15
      mode:
        output: true
      inverted: false

  - platform: gpio
    name: "GardenControl Ventil_1"
    id: gardencontrol_sw_ventil_1
    restore_mode: ALWAYS_OFF
    pin:
      mcp23xxx: mcp23017_bot
      number: 0
      mode:
        output: true
      inverted: false
    on_turn_on: 
      - switch.turn_on: gardencontrol_led_ventil_1 
    on_turn_off: 
      - switch.turn_off: gardencontrol_led_ventil_1 
  - platform: gpio
    name: "GardenControl Ventil_2"
    restore_mode: ALWAYS_OFF
    pin:
      mcp23xxx: mcp23017_bot
      number: 1
      mode:
        output: true
      inverted: false  
    on_turn_on: 
      - switch.turn_on: gardencontrol_led_ventil_2
    on_turn_off: 
      - switch.turn_off: gardencontrol_led_ventil_2
  - platform: gpio
    name: "GardenControl Ventil_3"
    restore_mode: ALWAYS_OFF
    pin:
      mcp23xxx: mcp23017_bot
      number: 2
      mode:
        output: true
      inverted: false      
    on_turn_on: 
      - switch.turn_on: gardencontrol_led_ventil_3
    on_turn_off: 
      - switch.turn_off: gardencontrol_led_ventil_3
  - platform: gpio
    name: "GardenControl Ventil_4"
    restore_mode: ALWAYS_OFF
    pin:
      mcp23xxx: mcp23017_bot
      number: 3
      mode:
        output: true
      inverted: false 
    on_turn_on: 
      - switch.turn_on: gardencontrol_led_ventil_4
    on_turn_off: 
      - switch.turn_off: gardencontrol_led_ventil_4
  - platform: gpio
    name: "GardenControl Ventil_5"
    restore_mode: ALWAYS_OFF
    pin:
      mcp23xxx: mcp23017_bot
      number: 4
      mode:
        output: true
      inverted: false       
    on_turn_on: 
      - switch.turn_on: gardencontrol_led_ventil_5
    on_turn_off: 
      - switch.turn_off: gardencontrol_led_ventil_5
  - platform: gpio
    name: "GardenControl Ventil_6"
    restore_mode: ALWAYS_OFF
    pin:
      mcp23xxx: mcp23017_bot
      number: 5
      mode:
        output: true
      inverted: false
    on_turn_on: 
      - switch.turn_on: gardencontrol_led_ventil_6
    on_turn_off: 
      - switch.turn_off: gardencontrol_led_ventil_6
  - platform: gpio
    name: "GardenControl Ventil_7"
    restore_mode: ALWAYS_OFF
    pin:
      mcp23xxx: mcp23017_bot
      number: 6
      mode:
        output: true
      inverted: false
    on_turn_on: 
      - switch.turn_on: gardencontrol_led_ventil_7
    on_turn_off: 
      - switch.turn_off: gardencontrol_led_ventil_7
  - platform: gpio
    name: "GardenControl Ventil_8"
    restore_mode: ALWAYS_OFF
    pin:
      mcp23xxx: mcp23017_bot
      number: 7
      mode:
        output: true
      inverted: false
    on_turn_on: 
      - switch.turn_on: gardencontrol_led_ventil_8
    on_turn_off: 
      - switch.turn_off: gardencontrol_led_ventil_8
  - platform: gpio
    name: "GardenControl Ventil_9"
    restore_mode: ALWAYS_OFF
    pin:
      mcp23xxx: mcp23017_bot
      number: 8
      mode:
        output: true
      inverted: false
    on_turn_on: 
      - switch.turn_on: gardencontrol_led_ventil_9
    on_turn_off: 
      - switch.turn_off: gardencontrol_led_ventil_9
  - platform: gpio
    name: "GardenControl Ventil_10"
    restore_mode: ALWAYS_OFF
    pin:
      mcp23xxx: mcp23017_bot
      number: 9
      mode:
        output: true
      inverted: false
    on_turn_on: 
      - switch.turn_on: gardencontrol_led_ventil_10
    on_turn_off: 
      - switch.turn_off: gardencontrol_led_ventil_10
  - platform: gpio
    name: "GardenControl Ventil_11"
    restore_mode: ALWAYS_OFF
    pin:
      mcp23xxx: mcp23017_bot
      number: 10
      mode:
        output: true
      inverted: false
    on_turn_on: 
      - switch.turn_on: gardencontrol_led_ventil_11
    on_turn_off: 
      - switch.turn_off: gardencontrol_led_ventil_11
  - platform: gpio
    name: "GardenControl Ventil_12"
    restore_mode: ALWAYS_OFF
    pin:
      mcp23xxx: mcp23017_bot
      number: 11
      mode:
        output: true
      inverted: false
    on_turn_on: 
      - switch.turn_on: gardencontrol_led_ventil_12
    on_turn_off: 
      - switch.turn_off: gardencontrol_led_ventil_12

  - platform: gpio
    name: "GardenControl Relais_1"
    restore_mode: ALWAYS_OFF
    pin:
      mcp23xxx: mcp23017_bot
      number: 12
      mode:
        output: true
      inverted: false
    on_turn_on: 
      - switch.turn_on: gardencontrol_led_relais_1
    on_turn_off: 
      - switch.turn_off: gardencontrol_led_relais_1
  - platform: gpio
    name: "GardenControl Relais_2"
    restore_mode: ALWAYS_OFF
    pin:
      mcp23xxx: mcp23017_bot
      number: 13
      mode:
        output: true
      inverted: false
    on_turn_on: 
      - switch.turn_on: gardencontrol_led_relais_2
    on_turn_off: 
      - switch.turn_off: gardencontrol_led_relais_2

  - platform: gpio
    name: "GardenControl Ventil_1 LED"
    id: gardencontrol_led_ventil_1
    internal: True
    pin:
      pcf8574: pcf8575
      number: 15
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "GardenControl Ventil_2 LED"
    id: gardencontrol_led_ventil_2
    internal: True
    pin:
      pcf8574: pcf8575
      number: 14
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "GardenControl Ventil_3 LED"
    id: gardencontrol_led_ventil_3
    internal: True
    pin:
      pcf8574: pcf8575
      number: 13
      mode:
        output: true
      inverted: true      
  - platform: gpio
    name: "GardenControl Ventil_4 LED"
    id: gardencontrol_led_ventil_4
    internal: True
    pin:
      pcf8574: pcf8575
      number: 12
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "GardenControl Ventil_5 LED"
    id: gardencontrol_led_ventil_5
    internal: True
    pin:
      pcf8574: pcf8575
      number: 11
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "GardenControl Ventil_6 LED"
    id: gardencontrol_led_ventil_6
    internal: True
    pin:
      pcf8574: pcf8575
      number: 10
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "GardenControl Ventil_7 LED"
    id: gardencontrol_led_ventil_7
    internal: True
    pin:
      pcf8574: pcf8575
      number: 9
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "GardenControl Ventil_8 LED"
    id: gardencontrol_led_ventil_8
    internal: True
    pin:
      pcf8574: pcf8575
      number: 8
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "GardenControl Ventil_9 LED"
    id: gardencontrol_led_ventil_9
    internal: True
    pin:
      pcf8574: pcf8575
      number: 7
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "GardenControl Ventil_10 LED"
    id: gardencontrol_led_ventil_10
    internal: True
    pin:
      pcf8574: pcf8575
      number: 6
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "GardenControl Ventil_11 LED"
    id: gardencontrol_led_ventil_11
    internal: True
    pin:
      pcf8574: pcf8575
      number: 5
      mode:
        output: true
      inverted: true      
  - platform: gpio
    name: "GardenControl Ventil_12 LED"
    id: gardencontrol_led_ventil_12
    internal: True
    pin:
      pcf8574: pcf8575
      number: 4
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "GardenControl Relais_1 LED"
    id: gardencontrol_led_relais_1
    internal: True
    pin:
      pcf8574: pcf8575
      number: 3
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "GardenControl Relais_2 LED"
    id: gardencontrol_led_relais_2
    internal: True
    pin:
      pcf8574: pcf8575
      number: 2
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "GardenControl MQTT LED"
    id: gardencontrol_mqtt_led
    pin:
      pcf8574: pcf8575
      number: 1
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "GardenControl 24VAC LED"
    id: gardencontrolPWRLed
    pin:
      pcf8574: pcf8575
      number: 0
      mode:
        output: true
      inverted: true
 


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO14
      inverted: true
    name: "GardenControl BIN-Input_1"
    filters:
      - delayed_on: 10ms

  - platform: gpio
    pin:
      number: GPIO16
      inverted: true
    name: "GardenControl BIN-Input_2"
    filters:
      - delayed_on: 10ms

  - platform: gpio
    name: "GardenControl HW-ID1"
    id: gardenControl_HWID1
    pin:
      mcp23xxx: mcp23017_top
      number: 0
      mode:
        input: true
        pullup: true
      inverted: false  
  - platform: gpio
    name: "GardenControl HW-ID2"
    id: gardenControl_HWID2
    pin:
      mcp23xxx: mcp23017_top
      number: 1
      mode:
        input: true
        pullup: true
      inverted: false  
  - platform: gpio
    name: "GardenControl HW-ID3"
    id: gardenControl_HWID3
    pin:
      mcp23xxx: mcp23017_top
      number: 2
      mode:
        input: true
        pullup: true
      inverted: false      
  - platform: gpio
    name: "GardenControl 12V ERROR"
    id: error12V
    pin:
      mcp23xxx: mcp23017_top
      number: 8
      mode:
        input: true
      inverted: false        
  - platform: gpio
    name: "GardenControl 24V ERROR"
    id: error24V
    pin:
      mcp23xxx: mcp23017_top
      number: 9
      mode:
        input: true
        pullup: false
      inverted: false 
  - platform: gpio
    name: "GardenControl 5V ERROR"
    id: error5V
    pin:
      mcp23xxx: mcp23017_top
      number: 10
      mode:
        input: true
        pullup: false
      inverted: true         

sensor:
  - platform: adc
    pin: GPIO32
    name: "GardenControl ADC_1"
    state_class: "measurement"
    accuracy_decimals: 2
    update_interval: 2s  
    attenuation: 11db   # max. Messbereich ca. 3.3V
    filters:
      multiply: 4
  - platform: adc
    pin: GPIO33
    name: "GardenControl ADC_2"
    state_class: "measurement"
    accuracy_decimals: 2
    update_interval: 2s  
    attenuation: 11db   # max. Messbereich ca. 3.3V
    filters:
      multiply: 4
  - platform: adc
    pin: GPIO34
    name: "GardenControl ADC_3"
    state_class: "measurement"
    accuracy_decimals: 2
    update_interval: 2s  
    attenuation: 11db   # max. Messbereich ca. 3.3V
    filters:
      multiply: 4
  - platform: adc
    pin: GPIO35
    name: "GardenControl ADC_4"
    state_class: "measurement"
    accuracy_decimals: 2
    update_interval: 2s    
    attenuation: 11db   # max. Messbereich ca. 3.3V
    filters:
      multiply: 4    
  - platform: adc
    pin: GPIO39
    id: gardendontrol_HW_ID_TOP_vlaue
    name: "GardenControl HW-ID Value"
    state_class: "measurement"
    accuracy_decimals: 2
    attenuation: 11db   # max. Messbereich ca. 3.3V
    filters:
      multiply: 1.0
     

  - platform: ads1115
    multiplexer: 'A1_GND'
    gain: 2.048
    name: "GardenControl 4-20mA CH1"
    update_interval: 3s  
    unit_of_measurement: "mA"
    device_class: current
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      multiply: 10
  - platform: ads1115
    multiplexer: 'A0_GND'
    gain: 2.048
    name: "GardenControl 4-20mA CH2"
    update_interval: 3s  
    unit_of_measurement: "mA"
    device_class: current
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      multiply: 10
  - platform: ads1115
    multiplexer: 'A2_GND'
    gain: 2.048
    name: "GardenControl 4-20mA CH1 ERROR"
    id: gardencontrol_ch1_4_20ma_adc_value
    unit_of_measurement: "V"
    update_interval: 3s  
  - platform: ads1115
    multiplexer: 'A3_GND'
    gain: 2.048
    name: "GardenControl 4-20mA CH2 ERROR"   
    id: gardencontrol_ch2_4_20ma_adc_value
    unit_of_measurement: "V"
    update_interval: 3s  

  - platform: template
    name: "GardenControl BOT HW-ID" 
    lambda: |- 
      if(id(gardenControl_HWID2).state == 0 && id(gardenControl_HWID2).state == 0 && id(gardenControl_HWID3).state == 1)
      {
        return 5.0;
      } else {
        return 0.0;
      }
    update_interval: 1.31s   

  - platform: template
    name: "GardenControl TOP HW-ID" 
    lambda: |- 
      float val;
      ESP_LOGD("gardencontrol", "ADC:%f", id(gardendontrol_HW_ID_TOP_vlaue).state);
      if(id(gardendontrol_HW_ID_TOP_vlaue).state > 3.1 )
      {
        val = 0.3;
      } else {
        val = 0.0;
      }
      /* auf eine Nachkommastelle runden */
      return round(val * 10.0) / 10.0;
    update_interval: 1.43s     

  # S0 counter 
  - platform: pulse_counter
    pin: GPIO17
    id: pulse_counter_id
    unit_of_measurement: 'kW'
    name: 'GardenControl Power Meter House'
    filters:
      - multiply: 0.06  # (60s/1000 pulses per kWh)

    total:
      unit_of_measurement: 'kWh'
      name: 'GardenControl Energy Meter House'
      filters:
        - multiply: 0.001  # (1/1000 pulses per kWh)

interval:
  - interval: 1s
    then:
      - lambda: |-
          if (id(error5V).state || id(error12V).state > 0 || id(error24V).state > 0 || id(gardencontrol_ch1_4_20ma_adc_value).state > 2 || id(gardencontrol_ch2_4_20ma_adc_value).state > 2) {
            id(gardenControlErrorLed).turn_on();
          } else {
            id(gardenControlErrorLed).turn_off();
          }

  - interval: 1.1s
    then:
      if:
        condition:
          mqtt.connected:
        then:
          - logger.log: MQTT is connected!
          - switch.turn_on: gardencontrol_mqtt_led
        else:
          - switch.turn_off: gardencontrol_mqtt_led

